#!/usr/bin/env python3
"""Full per-subtest pass-rate table (appendix) + a top-spread slide figure.

Two outputs from results/expansion/analysis/test_summary.csv:

1. ``subtest_full_table.{tex,csv}`` — every retained (task, subtest): mean pass
   rate and model range (min--max) across valid models. This is the exhaustive
   companion to the hand-curated 11-row slide, so the slide's selection cannot be
   read as cherry-picking.
2. ``slides_subtest_top_spread.png`` — the K subtests with the largest model
   disagreement (max-min pass rate). A principled, objective slide alternative:
   these are the subtests where architecture/training matters most.

Exclusions (consistent with the rest of the project):
- XSTest is out of scope (regex DIR analysed separately).
- Dream reruns (steps=64) are validated clean, so all Dream cells are retained;
  test_summary.csv already prefers the rerun dirs.
"""

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent.parent
TEST_CSV = ROOT / "results/expansion/analysis/test_summary.csv"
OUT_DIR = ROOT / "results/expansion/analysis"
FIG_DIR = ROOT / "paper/fig"

EXCLUDE_TASKS = {"xstest"}
EXCLUDE_MODELS: set[str] = set()
# Dream reruns (2026-06-07, steps=64) validated clean — no Dream cells excluded.
DREAM_INVALID_TASKS: set[str] = set()

TASK_ORDER = ["sentiment", "qqp", "squad", "mnli", "paws", "anli", "wildguard"]
TASK_LABEL = {
    "sentiment": "Sentiment", "qqp": "QQP", "squad": "SQuAD", "mnli": "MNLI",
    "paws": "PAWS", "anli": "ANLI", "wildguard": "WildGuard",
}


def is_valid(model_key: str, task: str) -> bool:
    if task in EXCLUDE_TASKS or model_key in EXCLUDE_MODELS:
        return False
    if model_key == "dream" and task in DREAM_INVALID_TASKS:
        return False
    return True


def load_subtests():
    rows = list(csv.DictReader(open(TEST_CSV)))
    # group pass rates per (task, test_type, capability, test_name)
    grp = defaultdict(list)
    for r in rows:
        if not is_valid(r["model_key"], r["task"]):
            continue
        key = (r["task"], r["test_type"], r["capability"], r["test_name"])
        grp[key].append(float(r["pass_rate"]))
    out = []
    for (task, ttype, cap, name), vals in grp.items():
        out.append({
            "task": task, "test_type": ttype, "capability": cap, "test_name": name,
            "n_models": len(vals),
            "mean": 100 * sum(vals) / len(vals),
            "lo": 100 * min(vals), "hi": 100 * max(vals),
            "spread": 100 * (max(vals) - min(vals)),
        })
    return out


def _tex_escape(s: str) -> str:
    for a, b in [("&", r"\&"), ("%", r"\%"), ("_", r"\_"), ("#", r"\#"),
                 ("$", r"\$"), ("{", r"\{"), ("}", r"\}")]:
        s = s.replace(a, b)
    return s


def write_full_table(subtests):
    # CSV (all columns)
    csv_path = OUT_DIR / "subtest_full_table.csv"
    with csv_path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["task", "test_type", "capability",
                                          "test_name", "n_models", "mean", "lo", "hi", "spread"])
        w.writeheader()
        for s in sorted(subtests, key=lambda s: (TASK_ORDER.index(s["task"]) if s["task"] in TASK_ORDER else 99,
                                                 s["test_type"], -s["mean"])):
            w.writerow({k: (f"{s[k]:.1f}" if k in ("mean", "lo", "hi", "spread") else s[k])
                        for k in w.fieldnames})

    # LaTeX longtable, grouped by task
    lines = [
        r"% Auto-generated by scripts/analysis/build_subtest_appendix.py",
        r"% Full per-subtest pass rate (mean and model range) across valid models.",
        r"\begin{longtable}{@{}p{0.40\textwidth}llrr@{}}",
        r"\caption{Per-subtest pass rate across all retained models (mean and "
        r"min--max range). XSTest is analysed separately.}"
        r"\label{tab:subtest-full}\\",
        r"\toprule",
        r"\textbf{Subtest} & \textbf{Type} & \textbf{Capability} & "
        r"\textbf{Mean} & \textbf{Range} \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule \textbf{Subtest} & \textbf{Type} & \textbf{Capability} & "
        r"\textbf{Mean} & \textbf{Range} \\ \midrule \endhead",
        r"\bottomrule \endfoot",
    ]
    by_task = defaultdict(list)
    for s in subtests:
        by_task[s["task"]].append(s)
    for task in [t for t in TASK_ORDER if t in by_task]:
        lines.append(rf"\multicolumn{{5}}{{@{{}}l}}{{\textbf{{{TASK_LABEL[task]}}}}}\\")
        lines.append(r"\midrule")
        for s in sorted(by_task[task], key=lambda s: (s["test_type"], -s["mean"])):
            lines.append(
                rf"{_tex_escape(s['test_name'][:60])} & {s['test_type']} & "
                rf"{_tex_escape(s['capability'])} & {s['mean']:.0f}\% & "
                rf"{s['lo']:.0f}--{s['hi']:.0f} \\"
            )
        lines.append(r"\midrule")
    lines.append(r"\end{longtable}")
    tex_path = OUT_DIR / "subtest_full_table.tex"
    tex_path.write_text("\n".join(lines))
    return csv_path, tex_path


def write_top_spread_slide(subtests, k: int, slide_types):
    # Rank only within the robustness-valid scope (INV/DIR). MFT spread is
    # dominated by label-collapse 0-100 swings (the slide-9 caveat) and is not a
    # robustness signal, so it is excluded from the slide ranking (kept in the
    # full appendix table).
    pool = [s for s in subtests if s["test_type"] in slide_types]
    top = sorted(pool, key=lambda s: s["spread"], reverse=True)[:k]
    cell = [[f"{TASK_LABEL[s['task']]}: {s['test_name'][:42]} ({s['test_type']})",
             f"{s['mean']:.0f}", f"{s['lo']:.0f}--{s['hi']:.0f}", f"{s['spread']:.0f}"]
            for s in top]
    fig, ax = plt.subplots(figsize=(11.0, 0.42 * k + 1.0), dpi=180)
    ax.axis("off")
    table = ax.table(
        cellText=cell,
        colLabels=["Subtest (task: name, type)", "Mean", "Range", "Spread"],
        cellLoc="left", colLoc="left",
        colWidths=[0.64, 0.12, 0.14, 0.10],
        bbox=[0.01, 0.01, 0.98, 0.95],
    )
    table.auto_set_font_size(False)
    table.set_fontsize(8.6)
    for (r, c), cellobj in table.get_celld().items():
        cellobj.set_edgecolor("#cccccc")
        if r == 0:
            cellobj.set_text_props(weight="bold")
        if c >= 1:
            cellobj._loc = "center"
    ax.set_title(f"Top {k} INV/DIR subtests by model disagreement (max-min pass rate)",
                 fontsize=11, weight="bold", pad=8)
    out = FIG_DIR / "slides_subtest_top_spread.png"
    fig.savefig(out, bbox_inches="tight")
    plt.close(fig)
    return out, top


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--top-k", type=int, default=15)
    ap.add_argument("--slide-types", default="INV,DIR",
                    help="Test types eligible for the top-spread slide ranking.")
    args = ap.parse_args()
    slide_types = set(t.strip() for t in args.slide_types.split(","))

    subtests = load_subtests()
    print(f"Retained {len(subtests)} distinct subtests across "
          f"{len({s['task'] for s in subtests})} tasks.")

    csv_path, tex_path = write_full_table(subtests)
    fig_path, top = write_top_spread_slide(subtests, args.top_k, slide_types)

    print(f"Wrote: {csv_path.relative_to(ROOT)}")
    print(f"Wrote: {tex_path.relative_to(ROOT)}")
    print(f"Wrote: {fig_path.relative_to(ROOT)}")
    print(f"\nTop {args.top_k} highest-disagreement subtests:")
    print(f"  {'subtest':<52}{'mean':>6}{'range':>12}{'spread':>8}")
    for s in top:
        lbl = f"{s['task']}:{s['test_name'][:38]} ({s['test_type']})"
        print(f"  {lbl:<52}{s['mean']:>5.0f}%{s['lo']:>5.0f}-{s['hi']:<5.0f}{s['spread']:>7.0f}")


if __name__ == "__main__":
    main()
