#!/usr/bin/env python3
"""label_distribution_audit.py

Label-distribution audit: the validity companion to pass rates and
perturbation-coefficient ratios. For every (model, label-task) cell it reports the
predicted-label distribution, the majority-label share, and an engagement
flag (minority-label rate >= 10%). A model that pins one label is "rigid":
its INV stability is trivial, its DIR behaviour degenerate, and its
contraction gamma uninterpretable (see the label-engaged gamma treatment).

Covers the seven label tasks (sentiment, qqp, paws, mnli, anli, wildguard,
xstest); SQuAD is free-span and has no label prior to audit.

Outputs:
  results/expansion/analysis/label_audit.csv
  results/expansion/analysis/label_audit.tex   (paper-ready table)
  paper/fig/label_audit_distributions.png      (stacked-bar figure)
"""

from __future__ import annotations

import csv
import glob
import json
from collections import Counter
from pathlib import Path

OUT_DIR = Path("results/expansion/analysis")
TASKS = ["sentiment", "qqp", "paws", "mnli", "anli", "wildguard"]
MODELS = ["llada_instruct", "llada_moe", "dream",
          "llama_instruct", "mistral", "qwen", "gemma", "olmo"]
DISPLAY = {
    "llada_instruct": "LLaDA-8B", "llada_moe": "LLaDA-MoE", "dream": "Dream-7B",
    "llama_instruct": "Llama-3.1", "mistral": "Mistral-7B", "qwen": "Qwen2.5-7B",
    "gemma": "Gemma-2-9B", "olmo": "OLMo-2-7B",
}
PHASE2 = {"llada_instruct": "results/checklist/{}/llada_rerun_fixed",
          "llama_instruct": "results/checklist/{}/llama_rerun_fixed"}
ABBREV = {"duplicate": "dup", "not_duplicate": "ndup", "entailment": "ent",
          "contradiction": "con", "neutral": "neu", "positive": "pos",
          "negative": "neg", "comply": "cmp", "refuse": "ref"}
ENGAGED_MIN_MINORITY = 0.10


def run_dir(task: str, model: str) -> str | None:
    if model in PHASE2 and task in ("sentiment", "qqp", "squad"):
        base = PHASE2[model].format(task)
    else:
        base = f"results/expansion/checklist/{task}/{model}"
        rerun = f"results/expansion/checklist/{task}/{model}_rerun"
        if model == "dream" and glob.glob(f"{rerun}/checklist_summary.json"):
            base = rerun
    return base if glob.glob(f"{base}/examples_full_*.jsonl") else None


def main() -> None:
    rows = []
    for task in TASKS:
        for m in MODELS:
            base = run_dir(task, m)
            if base is None:
                continue
            c: Counter = Counter()
            f = glob.glob(f"{base}/examples_full_*.jsonl")[0]
            for line in open(f):
                c[json.loads(line)["predicted_label"]] += 1
            n = sum(c.values())
            top_label, top_n = c.most_common(1)[0]
            maj = top_n / n
            rows.append({
                "task": task, "model_key": m, "model": DISPLAY[m],
                "n_examples": n,
                "majority_label": top_label, "majority_share": maj,
                "minority_rate": 1 - maj,
                "engaged": (1 - maj) >= ENGAGED_MIN_MINORITY,
                "distribution": "; ".join(f"{k}:{v/n:.3f}" for k, v in c.most_common()),
            })
            print(f"{task:<10} {m:<15} maj={top_label[:12]:<12} {100*maj:5.1f}%"
                  f"  {'engaged' if (1-maj) >= ENGAGED_MIN_MINORITY else 'RIGID'}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with (OUT_DIR / "label_audit.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        for r in rows:
            w.writerow({k: (f"{v:.4f}" if isinstance(v, float) else v) for k, v in r.items()})
    print(f"\nWrote {OUT_DIR/'label_audit.csv'}")

    # paper-ready table: rows = models, cols = tasks, cell = majority label + share
    by = {(r["model_key"], r["task"]): r for r in rows}
    lines = [
        "% Auto-generated by scripts/analysis/label_distribution_audit.py",
        r"\begin{table}[H]\centering\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{l" + "c" * len(TASKS) + "}",
        r"\toprule",
        "Model & " + " & ".join(t for t in TASKS) + r" \\",
        r"\midrule",
    ]
    for m in MODELS:
        cells = []
        for t in TASKS:
            r = by.get((m, t))
            if r is None:
                cells.append("--")
                continue
            ab = ABBREV.get(r["majority_label"], str(r["majority_label"])[:4])
            s = f"{ab}\\,{100*r['majority_share']:.0f}"
            if not r["engaged"]:
                s = r"\textbf{" + s + "}"
            cells.append(s)
        lines.append(f"{DISPLAY[m]} & " + " & ".join(cells) + r" \\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Label-distribution audit: majority predicted label and its share"
        r" (\%) per model and suite, over all examples. \textbf{Bold}: rigid cells"
        r" (minority-label rate $<$10\%), where INV stability is partly trivial and"
        r" DIR behaviour may be degenerate or vacuous. Suite-level rigidity is a"
        r" necessary screen, not a sufficient one --- perturbation-coefficient validity is"
        r" diagnosed separately via dead pair-weight (see the label-engaged $\gamma$"
        r" discussion): Gemma's QQP ratio is corrupted despite an 89\% share that"
        r" narrowly escapes bold, while OLMo's survives despite bold. Pass rates"
        r" for bold cells should be read jointly with this table. SQuAD is"
        r" free-span and has no label prior to audit.}",
        r"\label{tab:label-audit}",
        r"\end{table}",
        "",
    ]
    (OUT_DIR / "label_audit.tex").write_text("\n".join(lines))
    print(f"Wrote {OUT_DIR/'label_audit.tex'}")

    _figure(rows)


def _figure(rows: list[dict]) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    LABEL_COLORS = {
        "duplicate": "#d62728", "not_duplicate": "#1f77b4",
        "entailment": "#2ca02c", "contradiction": "#d62728", "neutral": "#7f7f7f",
        "positive": "#2ca02c", "negative": "#d62728",
        "comply": "#1f77b4", "refuse": "#ff7f0e",
    }
    by = {(r["model_key"], r["task"]): r for r in rows}
    fig, axes = plt.subplots(2, 4, figsize=(16, 7), sharex=True)
    axes = axes.ravel()
    for ax_i, task in enumerate(TASKS):
        ax = axes[ax_i]
        ypos = list(range(len(MODELS)))[::-1]
        for y, m in zip(ypos, MODELS):
            r = by.get((m, task))
            if r is None:
                continue
            left = 0.0
            for part in r["distribution"].split("; "):
                lab, share = part.rsplit(":", 1)
                share = float(share)
                ax.barh(y, share, left=left, height=0.72,
                        color=LABEL_COLORS.get(lab, "#bcbd22"),
                        edgecolor="white", linewidth=0.4)
                if share > 0.12:
                    ax.text(left + share / 2, y, ABBREV.get(lab, lab[:4]),
                            ha="center", va="center", fontsize=7, color="white")
                left += share
            if not r["engaged"]:
                ax.text(1.02, y, "RIGID", va="center", fontsize=7,
                        color="#d62728", fontweight="bold")
        ax.set_yticks(ypos)
        ax.set_yticklabels([DISPLAY[m] for m in MODELS], fontsize=8)
        ax.set_title(task, fontsize=10)
        ax.set_xlim(0, 1.12)
        ax.axhline(4.5, color="black", linewidth=0.6, linestyle=":")
        ax.tick_params(axis="x", labelsize=7)
    axes[-1].axis("off")
    fig.suptitle("Predicted-label distributions per model and suite "
                 "(dotted line separates DLMs above from ARs below)", fontsize=11)
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    out = Path("paper/fig/label_audit_distributions.png")
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=160)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
